ARG TARGETARCH
FROM alpine:3.22
ARG TARGETARCH
COPY bin/cmsingbox-linux-${TARGETARCH} /usr/local/bin/cmsingbox
USER root
VOLUME ["/data"]
EXPOSE 9092/tcp 2080/tcp 53/tcp 53/udp
ENTRYPOINT ["/usr/local/bin/cmsingbox", "-data", "/data", "-port", "9092"]
